[package]
name = "wasm_tutorial"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.85"
getrandom = {version="0.4.3", features = ['wasm_js']}
magic_cap = { path = "../magic-cap/magic_cap" }
wasm-bindgen = "0.2.108"
wasm-bindgen-futures = "0.4.58"
#wasm_streams = "*"
web-sys = {version = "*", features = ['Document', 'Element', 'HtmlElement', 'Node', 'Window', 'Headers', 'Request', 'RequestInit', 'RequestMode', 'Response', 'console', 'ReadableStream', 'ReadableStreamDefaultReader', 'HtmlImageElement', 'Location']}
reqwest = { version = "0.13.4", features = ["blocking"] }
base64 = "0.23.1"

# [lints]
# workspace = true